import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/Components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next-pokemon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation></Navigation>

        <div className="container px-4">
          {children}
        </div>
      </body>
    </html>
  )
}
