import './globals.css'
import { Inter } from 'next/font/google'

import classNames from 'classnames'

import Navigation from '@/Components/core/Navigation'
import Footer from '@/Components/core/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next-pokemon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames(`${inter.className} flex flex-col min-h-screen`)}>
        <Navigation></Navigation>

        <div className="container px-4 mb-10">
          {children}
        </div>

        <Footer />
      </body>
    </html>
  )
}
